---
title: "Assessment Growth and Section Performance Analytics in R"
subtitle: "Public-Safe BOY/EOY Improvement Study"
author: "Grant McCurdy"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  github_document: default
  pdf_document:
    toc: false
    latex_engine: pdflatex
    md_extensions: -implicit_figures
fontsize: 11pt
geometry: margin=0.85in
colorlinks: true
urlcolor: blue
header-includes:
  - \usepackage{booktabs}
  - \usepackage{graphicx}
---

```{r build, include=FALSE, message=FALSE, warning=FALSE}
source(file.path("R", "model_utils.R"))
ensure_project_dirs()
```

```{r report, echo=FALSE, results='asis', message=FALSE, warning=FALSE}
source(file.path("R", "render_markdown_report.R"))
report_lines <- readLines(file.path("reports", "assessment_growth_section_performance_report.md"))
if (length(report_lines) > 0 && grepl("^# ", report_lines[1])) {
  report_lines <- report_lines[-1]
  if (length(report_lines) > 0 && report_lines[1] == "") {
    report_lines <- report_lines[-1]
  }
}
page_break_marker <- "<!-- PDF_PAGE_BREAK -->"
if (knitr::is_latex_output()) {
  report_lines <- gsub(page_break_marker, "\\newpage", report_lines, fixed = TRUE)
} else {
  report_lines <- gsub(page_break_marker, "", report_lines, fixed = TRUE)
}
cat(report_lines, sep = "\n")
```
